def BRANCH = "main"

pipeline {
    agent any
    options {
        skipDefaultCheckout(true)
    }
    stages {
        stage('checkout') {
            steps {
               cleanWs()
               script {
                  sh '''#!/bin/bash -xe
                     printenv
                     echo "====> ${CHANGE_BRANCH} ${BRANCH_NAME}"
                     if [ "${BRANCH_NAME}" = "main" ] ; then
                        BRANCH="main"
                     elif [ "${CHANGE_BRANCH}" != "null" ] ; then
                        BRANCH="${CHANGE_BRANCH}"
                     else
                        BRANCH="main"
                     fi
                     export DOCKER_CMDS="source /opt/*/environment* ; \
west init -m 'https://github.com/alifsemi/zephyr_alif.git' \
--mr ${BRANCH} --mf west.yml ; cd zephyr ; west update ; \
if [ \"x${BRANCH}\" = \"xmain\" ] ; then rm -rf build ; \
west build -b alif_e3_dk_rtss_hp samples/hello_world ; \
west build -b alif_e3_dk_rtss_he samples/hello_world -p ; \
west build -b alif_e7_dk_rtss_hp samples/hello_world -p ; \
west build -b alif_e7_dk_rtss_he samples/hello_world -p ; \
west build -b alif_b1_dk_rtss_he samples/hello_world -p ; \
west build -b alif_e1c_dk_rtss_he samples/hello_world -p ; \
else if ./scripts/checkpatch.pl \
--ignore=GERRIT_CHANGE_ID,EMAIL_SUBJECT,COMMIT_MESSAGE,\
COMMIT_LOG_LONG_LINE -g \
origin/${BRANCH}...origin/main ; then rm -rf build ; \
west build -b alif_e3_dk_rtss_hp samples/hello_world ; \
west build -b alif_e3_dk_rtss_he samples/hello_world -p ; \
west build -b alif_e7_dk_rtss_hp samples/hello_world -p ; \
west build -b alif_e7_dk_rtss_he samples/hello_world -p ; \
west build -b alif_b1_dk_rtss_he samples/hello_world -p ; \
west build -b alif_e1c_dk_rtss_he samples/hello_world -p ; \
else echo 'ERROR:scripts/checkpatch.pl detected errors/warnings.'; \
echo 'CMD:Run git diff --cached | ./scripts/checkpatch.pl - before \
committing' ; exit 1 ; fi ; fi"
                     git clone http://10.10.10.22/zephyr-build-scripts.git -b devkit-b0-v3.6
                     cd zephyr-build-scripts/docker
                     ./build-ubuntu-image.sh
                     ./ubuntu-builder
                  '''
               }
            }
        }
    }
}
