/* Copyright (c) 2024 Alif Semiconductor
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ZEPHYR_INCLUDE_ZEPHYR_DT_BINDINGS_CLOCK_ALIF_ENSEMBLE_CLOCKS_H_
#define ZEPHYR_INCLUDE_ZEPHYR_DT_BINDINGS_CLOCK_ALIF_ENSEMBLE_CLOCKS_H_

#include "alif_clocks_common.h"

/* soc specific registers */
/* register offset for VBAT_CLKCTL module */
#define ALIF_RTC_CLK_EN_REG           0x10U
/* end of soc specific registers */

/* Camera pixel clocks */
#define ALIF_CAMERA_PIX_SYST_ACLK  \
	ALIF_CLK_CFG(PER_MST, CAMERA_PIXCLK_CTRL, 0U, 1U, 0U, 1U, 4U)
#define ALIF_CAMERA_PIX_PLL_CLK3   \
	ALIF_CLK_CFG(PER_MST, CAMERA_PIXCLK_CTRL, 0U, 1U, 1U, 1U, 4U)

/* CDC200 pixel clocks */
#define ALIF_CDC200_PIX_SYST_ACLK  \
	ALIF_CLK_CFG(PER_MST, CDC200_PIXCLK_CTRL, 0U, 1U, 0U, 1U, 4U)
#define ALIF_CDC200_PIX_PLL_CLK3   \
	ALIF_CLK_CFG(PER_MST, CDC200_PIXCLK_CTRL, 0U, 1U, 1U, 1U, 4U)

/* CSI pixel clocks */
#define ALIF_CSI_CLK                \
	ALIF_CLK_CFG(PER_MST, PERIPH_CLK_ENA, 24U, 1U, 0U, 0U, 0U)
#define ALIF_CSI_PIX_SYST_ACLK      \
	ALIF_CLK_CFG(PER_MST, CSI_PIXCLK_CTRL, 0U, 1U, 0U, 1U, 4U)
#define ALIF_CSI_PIX_PLL_CLK3       \
	ALIF_CLK_CFG(PER_MST, CSI_PIXCLK_CTRL, 0U, 1U, 1U, 1U, 4U)

/* CPI clocks */
#define ALIF_CPI_CLK                \
	ALIF_CLK_CFG(PER_MST, PERIPH_CLK_ENA, 0U, 1U, 0U, 0U, 0U)
#define ALIF_LPCPI_CLK              \
	ALIF_CLK_CFG(M55HE, HE_CLK_ENA, 12U, 1U, 0U, 0U, 0U)
#define ALIF_LPCPI_PXL_CLK          \
	ALIF_CLK_CFG(M55HE, HE_CAMERA_PIXCLK, 0U, 1U, 0U, 0U, 0U)

/* DPI clock */
#define ALIF_DPI_CLK                \
	ALIF_CLK_CFG(PER_MST, PERIPH_CLK_ENA, 1U, 1U, 0U, 0U, 0U)

/* DSI clock */
#define ALIF_DSI_CLK                \
	ALIF_CLK_CFG(PER_MST, PERIPH_CLK_ENA, 28U, 1U, 0U, 0U, 0U)

/* GPU clock */
#define ALIF_GPU_CLK                \
	ALIF_CLK_CFG(PER_MST, PERIPH_CLK_ENA, 8U, 1U, 0U, 0U, 0U)

/* Ethernet clocks */
#define ALIF_ETHERNET_CLK           \
	ALIF_CLK_CFG(PER_MST, PERIPH_CLK_ENA, 12U, 1U, 0U, 0U, 0U)
#define ALIF_ETH_RMII_REFCLK_PIN    \
	ALIF_CLK_CFG(PER_MST, ETH_CTRL, 0U, 0U, 0U, 1U, 4U)
#define ALIF_ETH_RMII_PLL_CLK_50M    \
	ALIF_CLK_CFG(PER_MST, ETH_CTRL, 0U, 0U, 1U, 1U, 4U)

/* SD clock */
#define ALIF_SDC_CLK                \
	ALIF_CLK_CFG(PER_MST, PERIPH_CLK_ENA, 16U, 1U, 0U, 0U, 0U)

/* USB clock */
#define ALIF_USB_CLK                \
	ALIF_CLK_CFG(PER_MST, PERIPH_CLK_ENA, 20U, 1U, 0U, 0U, 0U)

/* MIPI clocks */
#define ALIF_MIPI_TXDPHY_CLK        \
	ALIF_CLK_CFG(PER_MST, MIPI_CKEN, 0U, 1U, 0U, 0U, 0U)
#define ALIF_MIPI_RXDPHY_CLK        \
	ALIF_CLK_CFG(PER_MST, MIPI_CKEN, 4U, 1U, 0U, 0U, 0U)
#define ALIF_MIPI_PLLREF_CLK        \
	ALIF_CLK_CFG(PER_MST, MIPI_CKEN, 8U, 1U, 0U, 0U, 0U)
#define ALIF_MIPI_BYPASS_CLK        \
	ALIF_CLK_CFG(PER_MST, MIPI_CKEN, 12U, 1U, 0U, 0U, 0U)

/* Backup SRAM clock */
#define ALIF_BACKUP_RAM_CLK         \
	ALIF_CLK_CFG(PER_SLV, EXPMST0_CTRL, 4U, 1U, 0U, 0U, 0U)

/* PDM clocks */
#define ALIF_PDM_76M8_CLK           \
	ALIF_CLK_CFG(PER_SLV, EXPMST0_CTRL, 8U, 1U, 0U, 1U, 9U)
#define ALIF_PDM_AUDIO_CLK          \
	ALIF_CLK_CFG(PER_SLV, EXPMST0_CTRL, 8U, 1U, 1U, 1U, 9U)
#define ALIF_LPPDM_76M8_CLK         \
	ALIF_CLK_CFG(M55HE, HE_CLK_ENA, 8U, 1U, 0U, 1U, 9U)
#define ALIF_LPPDM_AUDIO_CLK        \
	ALIF_CLK_CFG(M55HE, HE_CLK_ENA, 8U, 1U, 1U, 1U, 9U)

/* UART clocks */
#define ALIF_UART0_38M4_CLK         \
	ALIF_CLK_CFG(PER_SLV, UART_CTRL, 0U, 1U, 0U, 1U, 8U)
#define ALIF_UART0_SYST_PCLK        \
	ALIF_CLK_CFG(PER_SLV, UART_CTRL, 0U, 1U, 1U, 1U, 8U)
#define ALIF_UART1_38M4_CLK         \
	ALIF_CLK_CFG(PER_SLV, UART_CTRL, 1U, 1U, 0U, 1U, 9U)
#define ALIF_UART1_SYST_PCLK        \
	ALIF_CLK_CFG(PER_SLV, UART_CTRL, 1U, 1U, 1U, 1U, 9U)
#define ALIF_UART2_38M4_CLK         \
	ALIF_CLK_CFG(PER_SLV, UART_CTRL, 2U, 1U, 0U, 1U, 10U)
#define ALIF_UART2_SYST_PCLK        \
	ALIF_CLK_CFG(PER_SLV, UART_CTRL, 2U, 1U, 1U, 1U, 10U)
#define ALIF_UART3_38M4_CLK         \
	ALIF_CLK_CFG(PER_SLV, UART_CTRL, 3U, 1U, 0U, 1U, 11U)
#define ALIF_UART3_SYST_PCLK        \
	ALIF_CLK_CFG(PER_SLV, UART_CTRL, 3U, 1U, 1U, 1U, 11U)
#define ALIF_UART4_38M4_CLK         \
	ALIF_CLK_CFG(PER_SLV, UART_CTRL, 4U, 1U, 0U, 1U, 12U)
#define ALIF_UART4_SYST_PCLK        \
	ALIF_CLK_CFG(PER_SLV, UART_CTRL, 4U, 1U, 1U, 1U, 12U)
#define ALIF_UART5_38M4_CLK         \
	ALIF_CLK_CFG(PER_SLV, UART_CTRL, 5U, 1U, 0U, 1U, 13U)
#define ALIF_UART5_SYST_PCLK        \
	ALIF_CLK_CFG(PER_SLV, UART_CTRL, 5U, 1U, 1U, 1U, 13U)
#define ALIF_UART6_38M4_CLK         \
	ALIF_CLK_CFG(PER_SLV, UART_CTRL, 6U, 1U, 0U, 1U, 14U)
#define ALIF_UART6_SYST_PCLK        \
	ALIF_CLK_CFG(PER_SLV, UART_CTRL, 6U, 1U, 1U, 1U, 14U)
#define ALIF_UART7_38M4_CLK         \
	ALIF_CLK_CFG(PER_SLV, UART_CTRL, 7U, 1U, 0U, 1U, 15U)
#define ALIF_UART7_SYST_PCLK        \
	ALIF_CLK_CFG(PER_SLV, UART_CTRL, 7U, 1U, 1U, 1U, 15U)
#define ALIF_LPUART_CLK             \
	ALIF_CLK_CFG(AON, RTSS_HE_LPUART_CKEN, 0U, 1U, 0U, 0U, 0U)

/* CAN-FD clocks */
#define ALIF_CANFD0_HFOSC_CLK       \
	ALIF_CLK_CFG(PER_SLV, CANFD_CTRL, 12U, 1U, 0U, 1U, 16U)
#define ALIF_CANFD0_160M_CLK        \
	ALIF_CLK_CFG(PER_SLV, CANFD_CTRL, 12U, 1U, 1U, 1U, 16U)

/* I2S clocks */
#define ALIF_I2S0_76M8_CLK          \
	ALIF_CLK_CFG(PER_SLV, I2S0_CTRL, 12U, 1U, 0U, 1U, 20U)
#define ALIF_I2S0_AUDIO_CLK         \
	ALIF_CLK_CFG(PER_SLV, I2S0_CTRL, 12U, 1U, 1U, 1U, 20U)
#define ALIF_I2S1_76M8_CLK          \
	ALIF_CLK_CFG(PER_SLV, I2S1_CTRL, 12U, 1U, 0U, 1U, 20U)
#define ALIF_I2S1_AUDIO_CLK         \
	ALIF_CLK_CFG(PER_SLV, I2S1_CTRL, 12U, 1U, 1U, 1U, 20U)
#define ALIF_I2S2_76M8_CLK          \
	ALIF_CLK_CFG(PER_SLV, I2S2_CTRL, 12U, 1U, 0U, 1U, 20U)
#define ALIF_I2S2_AUDIO_CLK         \
	ALIF_CLK_CFG(PER_SLV, I2S2_CTRL, 12U, 1U, 1U, 1U, 20U)
#define ALIF_I2S3_76M8_CLK          \
	ALIF_CLK_CFG(PER_SLV, I2S3_CTRL, 12U, 1U, 0U, 1U, 20U)
#define ALIF_I2S3_AUDIO_CLK         \
	ALIF_CLK_CFG(PER_SLV, I2S3_CTRL, 12U, 1U, 1U, 1U, 20U)
#define ALIF_LPI2S_76M8_CLK         \
	ALIF_CLK_CFG(M55HE, HE_I2S_CTRL, 12U, 1U, 0U, 1U, 16U)
#define ALIF_LPI2S_AUDIO_CLK        \
	ALIF_CLK_CFG(M55HE, HE_I2S_CTRL, 12U, 1U, 1U, 1U, 16U)

/* I3C clock */
#define ALIF_I3C_CLK                \
	ALIF_CLK_CFG(PER_SLV, I3C_CTRL, 0U, 1U, 0U, 0U, 0U)

/* ADC clocks */
#define ALIF_ADC0_CLK               \
	ALIF_CLK_CFG(PER_SLV, ADC_CTRL, 0U, 1U, 0U, 0U, 0U)
#define ALIF_ADC1_CLK               \
	ALIF_CLK_CFG(PER_SLV, ADC_CTRL, 4U, 1U, 0U, 0U, 0U)
#define ALIF_ADC2_CLK               \
	ALIF_CLK_CFG(PER_SLV, ADC_CTRL, 8U, 1U, 0U, 0U, 0U)
#define ALIF_ADC24_CLK              \
	ALIF_CLK_CFG(PER_SLV, ADC_CTRL, 12U, 1U, 0, 0U, 0U)

/* DAC clocks */
#define ALIF_DAC0_CLK               \
	ALIF_CLK_CFG(PER_SLV, DAC_CTRL, 0U, 1U, 0U, 0U, 0U)
#define ALIF_DAC1_CLK               \
	ALIF_CLK_CFG(PER_SLV, DAC_CTRL, 4U, 1U, 0U, 0U, 0U)

/* Comparator clocks */
#define ALIF_CMP0_CLK               \
	ALIF_CLK_CFG(PER_SLV, CMP_CTRL, 0U, 1U, 0U, 0U, 0U)
#define ALIF_CMP1_CLK               \
	ALIF_CLK_CFG(PER_SLV, CMP_CTRL, 4U, 1U, 0U, 0U, 0U)
#define ALIF_CMP2_CLK               \
	ALIF_CLK_CFG(PER_SLV, CMP_CTRL, 8U, 1U, 0U, 0U, 0U)
#define ALIF_CMP3_CLK               \
	ALIF_CLK_CFG(PER_SLV, CMP_CTRL, 12U, 1U, 0U, 0U, 0U)

/* GPIO Debounce clocks */
#define ALIF_GPIO0_DB_CLK           \
	ALIF_CLK_CFG(PER_SLV, GPIO0_CTRL, 12U, 1U, 0U, 0U, 0U)
#define ALIF_GPIO1_DB_CLK           \
	ALIF_CLK_CFG(PER_SLV, GPIO1_CTRL, 12U, 1U, 0U, 0U, 0U)
#define ALIF_GPIO2_DB_CLK           \
	ALIF_CLK_CFG(PER_SLV, GPIO2_CTRL, 12U, 1U, 0U, 0U, 0U)
#define ALIF_GPIO3_DB_CLK           \
	ALIF_CLK_CFG(PER_SLV, GPIO3_CTRL, 12U, 1U, 0U, 0U, 0U)
#define ALIF_GPIO4_DB_CLK           \
	ALIF_CLK_CFG(PER_SLV, GPIO4_CTRL, 12U, 1U, 0U, 0U, 0U)
#define ALIF_GPIO5_DB_CLK           \
	ALIF_CLK_CFG(PER_SLV, GPIO5_CTRL, 12U, 1U, 0U, 0U, 0U)
#define ALIF_GPIO6_DB_CLK           \
	ALIF_CLK_CFG(PER_SLV, GPIO6_CTRL, 12U, 1U, 0U, 0U, 0U)
#define ALIF_GPIO7_DB_CLK           \
	ALIF_CLK_CFG(PER_SLV, GPIO7_CTRL, 12U, 1U, 0U, 0U, 0U)
#define ALIF_GPIO8_DB_CLK           \
	ALIF_CLK_CFG(PER_SLV, GPIO8_CTRL, 12U, 1U, 0U, 0U, 0U)
#define ALIF_GPIO9_DB_CLK           \
	ALIF_CLK_CFG(PER_SLV, GPIO9_CTRL, 12U, 1U, 0U, 0U, 0U)
#define ALIF_GPIO10_DB_CLK          \
	ALIF_CLK_CFG(PER_SLV, GPIO10_CTRL, 12U, 1U, 0U, 0U, 0U)
#define ALIF_GPIO11_DB_CLK          \
	ALIF_CLK_CFG(PER_SLV, GPIO11_CTRL, 12U, 1U, 0U, 0U, 0U)
#define ALIF_GPIO12_DB_CLK          \
	ALIF_CLK_CFG(PER_SLV, GPIO12_CTRL, 12U, 1U, 0U, 0U, 0U)
#define ALIF_GPIO13_DB_CLK          \
	ALIF_CLK_CFG(PER_SLV, GPIO13_CTRL, 12U, 1U, 0U, 0U, 0U)
#define ALIF_GPIO14_DB_CLK          \
	ALIF_CLK_CFG(PER_SLV, GPIO14_CTRL, 12U, 1U, 0U, 0U, 0U)

/* LPTIMER clocks */
#define ALIF_LPTIMER0_S32K_CLK      \
	ALIF_CLK_CFG(VBAT, TIMER_CLKSEL, 0U, 0U, 0U, 3U, 0U)
#define ALIF_LPTIMER0_128K_CLK      \
	ALIF_CLK_CFG(VBAT, TIMER_CLKSEL, 0U, 0U, 1U, 3U, 0U)
#define ALIF_LPTIMER0_LPTMR0_IO_PIN \
	ALIF_CLK_CFG(VBAT, TIMER_CLKSEL, 0U, 0U, 2U, 3U, 0U)
#define ALIF_LPTIMER1_S32K_CLK      \
	ALIF_CLK_CFG(VBAT, TIMER_CLKSEL, 0U, 0U, 0U, 3U, 4U)
#define ALIF_LPTIMER1_128K_CLK      \
	ALIF_CLK_CFG(VBAT, TIMER_CLKSEL, 0U, 0U, 1U, 3U, 4U)
#define ALIF_LPTIMER1_LPTMR1_IO_PIN \
	ALIF_CLK_CFG(VBAT, TIMER_CLKSEL, 0U, 0U, 2U, 3U, 4U)
#define ALIF_LPTIMER1_CASCADE_CLK   \
	ALIF_CLK_CFG(VBAT, TIMER_CLKSEL, 0U, 0U, 3U, 3U, 4U)
#define ALIF_LPTIMER2_S32K_CLK      \
	ALIF_CLK_CFG(VBAT, TIMER_CLKSEL, 0U, 0U, 0U, 3U, 8U)
#define ALIF_LPTIMER2_128K_CLK      \
	ALIF_CLK_CFG(VBAT, TIMER_CLKSEL, 0U, 0U, 1U, 3U, 8U)
#define ALIF_LPTIMER2_LPTMR2_IO_PIN \
	ALIF_CLK_CFG(VBAT, TIMER_CLKSEL, 0U, 0U, 2U, 3U, 8U)
#define ALIF_LPTIMER3_S32K_CLK      \
	ALIF_CLK_CFG(VBAT, TIMER_CLKSEL, 0U, 0U, 0U, 3U, 12U)
#define ALIF_LPTIMER3_128K_CLK      \
	ALIF_CLK_CFG(VBAT, TIMER_CLKSEL, 0U, 0U, 1U, 3U, 12U)
#define ALIF_LPTIMER3_LPTMR3_IO_PIN \
	ALIF_CLK_CFG(VBAT, TIMER_CLKSEL, 0U, 0U, 2U, 3U, 12U)
#define ALIF_LPTIMER3_CASCADE_CLK   \
	ALIF_CLK_CFG(VBAT, TIMER_CLKSEL, 0U, 0U, 3U, 3U, 12U)

/* LPRTC clocks */
#define ALIF_LPRTCA_CLK             \
	ALIF_CLK_CFG(VBAT, RTC_CLK_EN, 0U, 1U, 0U, 0U, 0U)

/* LPSPI clock */
#define ALIF_LPSPI_CLK              \
	ALIF_CLK_CFG(M55HE, HE_CLK_ENA, 16U, 1U, 0U, 0U, 0U)

/* NPU clocks */
#define ALIF_NPU_HP_CLK             \
	ALIF_CLK_CFG(M55HP, HP_CLK_ENA, 0U, 1U, 0U, 0U, 0U)
#define ALIF_NPU_HE_CLK             \
	ALIF_CLK_CFG(M55HE, HE_CLK_ENA, 0U, 1U, 0U, 0U, 0U)

/* DMA clocks */
#define ALIF_DMA0_CLK               \
	ALIF_CLK_CFG(PER_MST, PERIPH_CLK_ENA, 4U, 1U, 0U, 0U, 0U)
#define ALIF_DMA1_CLK               \
	ALIF_CLK_CFG(M55HP, HP_CLK_ENA, 4U, 1U, 0U, 0U, 0U)
#define ALIF_DMA2_CLK               \
	ALIF_CLK_CFG(M55HE, HE_CLK_ENA, 4U, 1U, 0U, 0U, 0U)

/* UTIMER clocks */
#define ALIF_UTIMER_CLK     ALIF_CLK(1U)

#endif /* ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_ALIF_CLOCK_CONTROL_H_ */
